name: proyecto-modulo-4-ferenc

services:
  mysql:
    image: mysql:8.0.41
    container_name: mysql-ferenc
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: ferenc
      MYSQL_PASSWORD: ferenc
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:8.0.0-alpine
    container_name: redis-ferenc
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
    mysql_data:
    redis_data:
